language: cpp
dist: trusty
sudo: required

compiler:
    - clang
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty

    packages:
      - gcc-7
      - g++-7
      - clang
      - cppcheck

install: 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

script:
    - make
    - make emi_test
    - make python_test
    - make unit_test
    - make cpp_check
