#ifndef AUTOTEST_H
#define AUTOTEST_H

#include <emiif.h>

#define TEST_NONBLOCK_NO_SENDATA                   0x0100
#define TEST_NONBLOCK_WITH_SENDATA                 0x0200
#define TEST_BLOCK_WITH_SENDATA_NO_RETDATA         0x0300
#define TEST_BLOCK_NO_SENDATA_NO_RETDATA           0x0400
#define TEST_BLOCK_WITH_SENDATA_WITH_RETDATA       0x0500
#define TEST_BLOCK_NO_SENDATA_WITH_RETDATA         0x0600

#endif
